/**:
  ros__parameters:
    inputs: ['ground_truth_cloud']
    ground_truth_cloud: # A name to identify the input source
      type: pointcloud # Supported types: pointcloud
      # topic: /merged_points_filtered
      topic: /merged_points_filtered
      queue_size: 10
      publish_on_update: true # Whether to publish the elevation map after a callback from this source.
      sensor_processor:
        type: laser
    map_frame_id: "map"
    robot_base_frame_id: "base_link"
    robot_pose_with_covariance_topic: "/fixposition/odometry"
    robot_pose_topic: "/fixposition/odometry"
    track_point_frame_id: "base_link"
    track_point_x: 0.0
    track_point_y: 0.0
    track_point_z: 0.0
    use_sim_time: true

